name: Coverage
on: [push, pull_request]

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: ziishaned/jest-reporter-action@0.0.1
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
